function GraphView({g,onPick}:{g:any;onPick:(name:string)=>void}){
  const [vp,setVp]=useState({scale:1,tx:0,ty:0}),[pos,setPos]=useState<Record<string,{x:number;y:number}>>({}),[hover,setHover]=useState<string|null>(null)
  const svgRef=React.useRef<SVGSVGElement>(null),dragRef=React.useRef<GraphDrag>({type:'none'}),lastNodeDragRef=React.useRef(false)
  if(!g)return null
  const layout=useMemo(()=>layoutGraph(g),[g]),pairs=[...g.edges].sort((a:any,b:any)=>b.weight-a.weight).slice(0,8),at=(n:any)=>pos[n.id]||{x:n.x,y:n.y}
  const fit=()=>fitGraph(layout.nodes),key=layout.nodes.map((n:any)=>n.id).join('|')
  useEffect(()=>{setPos({});setVp(fit())},[key])
  const toView=(x:number,y:number)=>{const r=svgRef.current?.getBoundingClientRect();return r?{x:(x-r.left)*VIEW_W/r.width,y:(y-r.top)*VIEW_H/r.height}:{x:0,y:0}}
  const toWorld=(x:number,y:number)=>{const p=toView(x,y);return{x:(p.x-vp.tx)/vp.scale,y:(p.y-vp.ty)/vp.scale}}
  const zoomAt=(x:number,y:number,f:number)=>{const p=toView(x,y);setVp(v=>{const scale=Math.min(MAX_SCALE,Math.max(MIN_SCALE,v.scale*f)),k=scale/v.scale;return{scale,tx:p.x-(p.x-v.tx)*k,ty:p.y-(p.y-v.ty)*k}})}
  const down=(e:React.PointerEvent)=>{if(e.button!==0||dragRef.current.type!=='none')return;const p=toView(e.clientX,e.clientY);dragRef.current={type:'canvas',pointerId:e.pointerId,startX:p.x,startY:p.y,tx:vp.tx,ty:vp.ty,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}
  const move=(e:React.PointerEvent)=>{const d=dragRef.current;if(d.type==='node'){const p=toWorld(e.clientX,e.clientY),dx=p.x-d.d,dy=p.y-d.dy;if(Math.hypot(dx,dy)>DRAG_THRESHOLD)d.moved=true;const n=layout.nodes.find((x:any)=>x.id===d.id);if(n){const r=n.r+20;setPos(o=>({...o,[d.id]:{x:clamp(d.nx+dx,r,VIEW_W-r),y:clamp(d.ny+dy,r,VIEW_H-r)}}))}return}if(d.type==='canvas'){const p=toView(e.clientX,e.clientY),dx=p.x-d.startX,dy=p.y-d.startY;if(Math.hypot(dx,dy)>DRAG_THRESHOLD)d.moved=true;setVp(v=>({...v,tx:d.tx+dx,ty:d.ty+dy}))}}
  const up=(e:React.PointerEvent)=>{const d=dragRef.current;lastNodeDragRef.current=d.type==='node'&&d.moved;if(d.type!=='none'&&e.currentTarget.hasPointerCapture?.(d.pointerId))e.currentTarget.releasePointerCapture(d.pointerId);dragRef.current={type:'none'};setHover(null)}
  const nodeDown=(e:React.PointerEvent,n:any)=>{e.stopPropagation();e.preventDefault();const p=toWorld(e.clientX,e.clientY),a=at(n);dragRef.current={type:'node',pointerId:e.pointerId,id:n.id,d:p.x,dy:p.y,nx:a.x,ny:a.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}
  const nodeClick=(e:React.MouseEvent,n:any)=>{e.stopPropagation();if(lastNodeDragRef.current){lastNodeDragRef.current=false;return}onPick(n.id)}
  const zoomButton=(f:number)=>{const r=svgRef.current?.getBoundingClientRect();if(r)zoomAt(r.left+r.width/2,r.top+r.height/2,f)}
  return <div className="graph-page"><h2>知识图谱</h2><p>节点大小代表错题数量，连线粗细代表共同出现的频率。可拖拽节点、空白区域平移，滚轮缩放，点击节点查看错题，悬停高亮关联。</p>
    {layout.nodes.length?<div className="knowledge-map"><div className="graph-stage"><svg ref={svgRef} viewBox={`0 0 ${VIEW_W} ${VIEW_H}`} role="img" aria-label="知识点关系图" onWheel={e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,e.deltaY<0?1.12:1/1.12)}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>
      <g transform={`translate(${vp.tx} ${vp.ty}) scale(${vp.scale})`}>
        <g className="graph-lines">{layout.edges.map((e:any)=>{const s=at(e.source),t=at(e.target),on=!hover||hover===e.source.id||hover===e.target.id;return <g key={e.source.id+'-'+e.target.id} className={`graph-edge${on?'':' dim'}`}><line x1={s.x} y1={s.y} x2={t.x} y2={t.y} strokeWidth={Math.min(7,1+e.weight)}/><text x={(s.x+t.x)/2} y={(s.y+t.y)/2}>{e.weight}次</text></g>})}</g>
        <g>{layout.nodes.map((n:any)=>{const p=at(n),near=new Set(layout.edges.filter((e:any)=>e.source.id===n.id||e.target.id===n.id).flatMap((e:any)=>[e.source.id,e.target.id]));return <g className={`graph-vertex${hover===n.id?' on':''}${hover&&hover!==n.id&&!near.has(n.id)?' dim':''}`} key={n.id} role="button" tabIndex={0} onPointerDown={e=>nodeDown(e,n)} onClick={e=>nodeClick(e,n)} onPointerEnter={()=>setHover(n.id)} onPointerLeave={()=>setHover(null)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onPick(n.id)}}><circle cx={p.x} cy={p.y} r={n.r} fill={n.color}/><text x={p.x} y={p.y+n.r+16} textAnchor="middle">{n.id} ({n.count})</text><title>{n.id}：{n.count} 道，掌握 {n.mastery}%，待复习 {n.due}</title></g>})}</g>
      </g></svg><div className="graph-controls"><button onClick={()=>zoomButton(1.2)}>＋</button><button onClick={()=>zoomButton(1/1.2)}>－</button><button onClick={()=>{setPos({});setVp(fit())}}>⟲</button></div><span className="graph-zoom">{Math.round(vp.scale*100)}%</span></div>
      <aside><h3>关联最强的知识点对</h3>{pairs.map((e:any)=><button key={e.source+e.target} onClick={()=>onPick(e.source)}><span>{e.source}</span><i>×</i><span>{e.target}</span><b>{e.weight} 次</b></button>)}{!pairs.length&&<p>需要至少一道包含两个知识点的错题。</p>}</aside></div>:<div className="empty">添加知识点后会生成关系图。</div>}</div>
}
type GraphDrag={type:'none'}|{type:'canvas';pointerId:number;startX:number;startY:number;tx:number;ty:number;moved:boolean}|{type:'node';pointerId:number;id:string;d:number;dy:number;nx:number;ny:number;moved:boolean}